### ISSUE TITLE
Using esplint with common eslint config extensions  (extends airbnb etc)

### ISSUE THREAD

**Issue by david-cord** [hjylewis/esplint#118]
Hello all,

First off, thank you for an excellent plugin which addresses a much needed use-case.  I was just wondering what's the best way to track enforcement of say some common eslint presets.

For example my `.eslintrc`

```
  "extends": [
    "airbnb",
    "airbnb/hooks",
    "airbnb-typescript",
    "prettier"
  ],
```

Is there a suggested way I can get these rules into the `.eslplintrc.js` without having to somehow manually explode all those configs into rules and specifying them inline?

Many thanks in advance!

**Comment by david-cord** [comment]
In the meantime i've used `eslint --print-config` to snapshot out the rules, and paste those in, however I'm hoping there's a more dynamic way.  

Any input appreciated.

**Comment by hjylewis** [comment]
Hello @david-cord! Thanks for opening this issue (sorry for the late reply)

A couple of ideas and questions so I understand your use case.

> In the meantime i've used eslint --print-config to snapshot out the rules, and paste those in, however I'm hoping there's a more dynamic way.

Why exactly do you need a dynamic way? Are you often adding new plugins and rules that you want to track and it's tedious to add the rules manually each time? 

Are you adding every rule on your eslint config to esplint?

---

The way to make it dynamic is to have `.espllintrc.js` run [eslint.calculateConfigForFile(filePath)](https://eslint.org/docs/developer-guide/nodejs-api#-eslintcalculateconfigforfilefilepath) and then export those rules. This is basically the automated version of your `eslint --print-config` approach.

Does that help?

**Comment by david-cord** [comment]
Hi @hjylewis, thank you for the response.

I wanted to track all linting rules not just the existing offending ones, to ensure no regressions in the wider codebase.

It's a very valid point about the need for it to be dynamic, you're right - this config does not change.  We're very happy with the implementation now using the `--print-config` to extract out the full rule-set from the plugins.

Happy to close this issue, and thanks again for a great plugin!
