### ISSUE TITLE
Support other tools

### ISSUE THREAD

**Issue by proxi** [hjylewis/esplint#85]
Did you consider supporting other tools? The core idea of enforcing monotonic decrease of a metric would be very useful in other contexts, such as migrating to TypeScript's `strict` mode or applying custom linters.

**Comment by hjylewis** [comment]
Yeah, I've been thinking the same thing. I think making the tool more generalized will be helpful. 

If you are interested in helping out, let me know. I don't have a ton of bandwidth at the moment. 

You might want to check out https://github.com/phenomnomnominal/betterer which might fit your usecase.
