### ISSUE TITLE
Add compact output for stats command

### ISSUE THREAD

**Issue by FelixGraf** [hjylewis/esplint#98]
First, thanks for this nice project!

I am working on a large legacy project with a couple of thousands eslint rule violations. In order to prioritize, which violations to tackle first, I would like to have a compact output for `esplint stats` that only outputs the rule and the number of violations without the file where the violation is.

Example:
`npx esplint stats --compact` outputs:
```
"implicit-arrow-linebreak": 1
"import/extensions": 15
"import/order": 239
```

I could make a pull request for that feature, if you think that this would be a valuable feature :)

**Comment by hjylewis** [comment]
Good idea. Feel free to open a pull request!

If you are feeling ambitious you could try to implement an API like [eslint formatters](https://eslint.org/docs/user-guide/formatters/#eslint-formatters) so anyone can define a custom format. Something like `npx esplint stats --format ./my-awesome-formatter.js`

That is obviously more work so feel free to stick with your original API `npx esplint stats --compact`

**Comment by FelixGraf** [comment]
I opened a pull request, but I stuck to the original proposed API `npx esplint stats --compact` :)

**Comment by hjylewis** [comment]
This can be found in version `0.9.3`
